version: "3.8"

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf
    container_name: stirling-pdf
    ports:
      - "8090:8080"
    volumes:
      - ./configs:/configs
      - ./customFiles:/customFiles
    environment:
      - DOCKER_ENABLE_SECURITY=false
    restart: unless-stopped
